### ISSUE TITLE
Code refactor

### ISSUE THREAD

**Issue by ifree** [amnesiaice/JupyterGit#1]
Try to improve your code quality, aim at modular, reusable, easy to understand.

**Comment by amnesiaice** [comment]
refract the code 

- to let the canvas control all the device information, such as z-buffer, point buffer, index buffer and so on.

- abstract the entity class to prepare the triangle cube and the model in the future.

- gradually discard the feature_manager module in the further work.

-  refract the test case to test each case individually.

- put the matplotlib API into one module to enable easilly switch between different API in the future.

**Comment by ifree** [comment]
let's have a talk on next week.
